const followedChannels = [
  {
    user: "casimito",
    title: "POST BRAZIL CUP!!!!!!!!!!!!!!!!!!!!",
    game: "Just Chatting",
    viewers: 294283,
    tags: ["Twitch"],
    avatar: "/assets/avatar/casimito.png",
    color: "#C0F500",
    live_preview_image: "/assets/live_preview/casimito-preview.jpg",
  },
  {
    user: "alanzoka",
    title: "TOP 1 IN ALL UNIVERSES",
    game: "Star Wars Jedi: Survivor",
    viewers: 10920,
    tags: ["Twitch"],
    avatar: "/assets/avatar/alanzoka.png",
    live_preview_image: "/assets/live_preview/alanzoka-preview.jpg",
  },
  {
    user: "YoDa",
    title: "MINECRAFT TODAY AT NOON",
    game: "League of Legends",
    viewers: 7467,
    tags: ["Twitch"],
    avatar: "/assets/avatar/YoDa.png",
    color: "#4156BE",
    live_preview_image: "/assets/live_preview/yoda-preview.jpg",
  },
  {
    user: "Baiano",
    title:
      "PRE-SHOW MSI ISLAND OF LEGENDS 🏝️ LOUD vs G2 🏝️ !Cuts @esacarry @minerva @mylonzete",
    game: "League of Legends",
    viewers: 7430,
    tags: ["Twitch"],
    avatar: "/assets/avatar/Baiano.png",
    color: "#FFA435",
    live_preview_image: "/assets/live_preview/baiano-preview.jpg",
  },
  {
    user: "frttt",
    title: "RANKED TRYHARD TO THE TOP - !classes !shop !liquid+",
    game: "VALORANT",
    viewers: 4300,
    tags: ["Twitch"],
    avatar: "/assets/avatar/frttt.png",
    live_preview_image: "/assets/live_preview/frttt-preview.jpg",
  },
  {
    user: "Coreano",
    title:
      "Rankeads 15s until about 18:00, then I take delay and play something else | !youtube !vods !loudclub",
    game: "VALORANT",
    viewers: 3405,
    tags: ["Twitch"],
    avatar: "/assets/avatar/Coreano.png",
    color: "#000000",
    live_preview_image: "/assets/live_preview/coreano-preview.jpg",
  },
  {
    user: "Felps",
    title: "497th | click.",
    game: "Cookie Clicker",
    viewers: 2231,
    tags: ["Twitch"],
    avatar: "/assets/avatar/Felps.png",
    color: "#FF3D6C",
    live_preview_image: "/assets/live_preview/felps-preview.jpg",
  },
  {
    user: "TFToddy",
    title: "#2 BR - 1763 PDLs - SEEKING THE TOP 1 BR!!!",
    game: "Teamfight Tactics",
    viewers: 1879,
    tags: ["Twitch"],
    avatar: "/assets/avatar/TFToddy.png",
    color: "#1E1B5E",
    live_preview_image: "/assets/live_preview/tftoddy-preview.jpg",
  },
  {
    user: "Prizzaa",
    title: "LET'S GOSSIP YES and go to tokyo later",
    game: "Just Chatting",
    viewers: 723,
    tags: ["Twitch"],
    avatar: "/assets/avatar/Prizzaa.png",
    color: "#FAB3FF",
    live_preview_image: "/assets/live_preview/prizzaa-preview.jpg",
  },
  {
    user: "laribasgal",
    title: "QUERO CAFEEEEEEE !zap !rules",
    game: "VALORANT",
    viewers: 623,
    tags: ["Twitch"],
    avatar: "/assets/avatar/laribasgal.png",
    color: "#F5F064",
    live_preview_image: "/assets/live_preview/laribasgal-preview.jpg",
  },
  {
    user: "nuuhfps",
    title: "🟢🟢 [Radiant] I'm playing badly 🟢🟢 - !Samsung !aimlab !exitlag",
    game: "VALORANT",
    viewers: 561,
    tags: ["Twitch"],
    avatar: "/assets/avatar/nuuhfps.png",
    color: "#EFF133",
    live_preview_image: "/assets/live_preview/nuuhfps-preview.jpg",
  },
  {
    user: "PatoPapao",
    title: "sub out of pity? 🥺 | !schedule !pokemon",
    game: "League of Legends",
    viewers: 532,
    tags: ["Twitch"],
    avatar: "/assets/avatar/PatoPapao.png",
    color: "#00C7AC",
    live_preview_image: "/assets/live_preview/patopapao-preview.jpg",
  },
];

const recommendedChannels = [
  {
    user: "Recommended 1",
    game: "Minecraft",
    viewers: 1100,
    tags: ["English"],
  },
  {
    user: "Recommended 2",
    game: "Terraria",
    viewers: 70,
    tags: ["English"],
  },
  {
    user: "Recommended 3",
    game: "VALORANT",
    viewers: 4800,
    tags: ["English"],
  },
  {
    user: "Recommended 4",
    game: "Overwatch 2",
    viewers: 19,
    tags: ["English"],
  },
  {
    user: "Recommended 5",
    game: "League of Legends",
    viewers: 436,
    tags: ["English"],
  },
  {
    user: "Recommended 6",
    game: "Teamfight Tactics",
    viewers: 248,
    tags: ["English"],
  },
];

const games = [
  {
    name: "VALORANT",
    image: "/assets/games/valorant.jpg",
    viewers: 108200,
    tags: ["Shooter", "FPS"],
  },
  {
    name: "Cookie Clicker",
    image: "/assets/games/cookie-clicker.jpg",
    viewers: 2231,
    tags: ["Point and Click"],
  },
  {
    name: "Minecraft",
    image: "/assets/games/minecraft.jpg",
    viewers: 136620,
    tags: ["MMO"],
  },
  {
    name: "Software and Game Development",
    image: "/assets/games/development.jpg",
    viewers: 5230,
    tags: ["IRL", "Creative"],
  },
  {
    name: "Just Chatting",
    image: "/assets/games/just-chatting.jpg",
    viewers: 376239,
    tags: ["IRL"],
  },
  {
    name: "Music",
    image: "/assets/games/music.jpg",
    viewers: 32502,
    tags: ["IRL", "Creative"],
  },
  {
    name: "League of Legends",
    image: "/assets/games/league-of-legends.jpg",
    viewers: 93854,
    tags: ["MOBA", "Action"],
  },
  {
    name: "Teamfight Tactics",
    image: "/assets/games/teamfight-tactics.jpg",
    viewers: 16440,
    tags: ["Strategy"],
  },
  {
    name: "Genshin Impact",
    image: "/assets/games/genshin-impact.jpg",
    viewers: 26602,
    tags: ["Action", "RPG"],
  },
  {
    name: "Sports",
    image: "/assets/games/sports.jpg",
    viewers: 446829,
    tags: ["IRL"],
  },
  {
    name: "Pokémon Scarlet/Violet",
    image: "/assets/games/pokemon-scarlet.jpg",
    viewers: 61320,
    tags: ["RPG"],
  },
  {
    name: "Red Dead Redemption 2",
    image: "/assets/games/red-read-redemption.jpg",
    viewers: 2630,
    tags: ["Action"],
  },
  {
    name: "God of War Ragnarök",
    image: "/assets/games/gow-ragnarock.jpg",
    viewers: 16720,
    tags: ["Action"],
  },
  {
    name: "Overwatch 2",
    image: "/assets/games/overwatch-2.jpg",
    viewers: 42320,
    tags: ["FPS", "Shooter"],
  },
  {
    name: "Celeste",
    image: "/assets/games/celeste.jpg",
    viewers: 4120,
    tags: ["Platformer"],
  },
  {
    name: "Art",
    image: "/assets/games/art.jpg",
    viewers: 12720,
    tags: ["Creative", "IRL"],
  },
];

const categories = [
  {
    name: "Games",
    image: "/assets/categories/games.svg",
  },
  {
    name: "IRL",
    image: "/assets/categories/irl.svg",
  },
  {
    name: "Music",
    image: "/assets/categories/music.svg",
  },
  {
    name: "Esports",
    image: "/assets/categories/esports.svg",
  },
  {
    name: "Creative",
    image: "/assets/categories/creative.svg",
  },
];

export { followedChannels, recommendedChannels, games, categories };
